# Google Cloud Build configuration for AI Server (Artifact Registry)
# Pre-requisite: create an Artifact Registry repository named "servio-ai"
# in region "us-west1" (Console → Artifact Registry → Create Repository)
steps:
  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-west1-docker.pkg.dev/$PROJECT_ID/servio-ai/ai-server:$COMMIT_SHA"
      - "-t"
      - "us-west1-docker.pkg.dev/$PROJECT_ID/servio-ai/ai-server:latest"
      - "-f"
      - "Dockerfile"
      - "."

  # Push image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-west1-docker.pkg.dev/$PROJECT_ID/servio-ai/ai-server:$COMMIT_SHA"

  # Push latest tag
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-west1-docker.pkg.dev/$PROJECT_ID/servio-ai/ai-server:latest"

# Store images in Artifact Registry
images:
  - "us-west1-docker.pkg.dev/$PROJECT_ID/servio-ai/ai-server:$COMMIT_SHA"
  - "us-west1-docker.pkg.dev/$PROJECT_ID/servio-ai/ai-server:latest"

# Build timeout
timeout: 1200s
