# Google Cloud Build configuration for AI Server
steps:
  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/servio-ai:$COMMIT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/servio-ai:latest"
      - "-f"
      - "Dockerfile"
      - "."

  # Push image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/servio-ai:$COMMIT_SHA"

  # Push latest tag
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/servio-ai:latest"

# Store images in Container Registry
images:
  - "gcr.io/$PROJECT_ID/servio-ai:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/servio-ai:latest"

# Build timeout
timeout: 1200s
