# Google Cloud Build (1ª geração) — Build & Deploy para Cloud Run
# Pré‑requisitos:
# - Artifact Registry habilitado e repositório "servio-ai" (Docker) na região us-west1
# - APIs habilitadas: run.googleapis.com, cloudbuild.googleapis.com, artifactregistry.googleapis.com

substitutions:
  _REGION: us-west1
  _SERVICE: servio-ai
  # Nome do repositório do Artifact Registry (atenção: hífen, não ponto)
  _REPO: servio-ai
  _IMAGE: ai-server

steps:
  # 1) Build da imagem Docker
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-west1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA"
      - "-t"
      - "us-west1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:latest"
      - "-f"
      - "Dockerfile"
      - "."

  # 2) Push da imagem
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-west1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-west1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:latest"

  # 3) Deploy no Cloud Run usando a imagem (as variáveis de ambiente já existentes no serviço são preservadas)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - "${_SERVICE}"
      - "--image=us-west1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--allow-unauthenticated"

# Artefatos publicados
images:
  - "us-west1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA"
  - "us-west1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:latest"

timeout: 1200s

# Logging options required by some org policies when using a user-managed
# service account for Cloud Build. This avoids the need to configure a
# GCS logs bucket explicitly.
options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
